export const recommendationStartingList = [
    {
        url: "https://example.com/resource1",
        name: "Resource 1",
        author: "John Doe",
        description: "A fantastic resource for learning",
        content_type: "Article",
        build_phase: "Production",
        creation_date: new Date("2023-09-13"),
        user_id: 1,
        recommendation_type: "I recommend this resource after having used it",
        reason: "It helped me understand the topic better.",
        likes: 10,
        dislikes: 2,
        tags: ["learning", "education"],
        comments: [
            {
                user_name: "Alice",
                comment: "I totally agree! This resource is amazing.",
            },
            {
                user_name: "Bob",
                comment: "I found it very helpful as well.",
            },
        ],
    },
    {
        url: "https://example.com/resource2",
        name: "Resource 2",
        author: "Jane Smith",
        description: "A comprehensive video tutorial series",
        content_type: "Video",
        build_phase: "Testing",
        creation_date: new Date("2023-09-12"),
        user_id: 2,
        recommendation_type:
            "I haven't used this resource but it looks promising",
        reason: "I plan to check it out soon.",
        likes: 5,
        dislikes: 0,
        tags: ["tutorial", "video"],
        comments: [],
    },
    {
        url: "https://example.com/resource3",
        name: "Resource 3",
        author: "Mike Johnson",
        description: "A book with in-depth insights",
        content_type: "Book",
        build_phase: "Development",
        creation_date: new Date("2023-09-11"),
        user_id: 3,
        recommendation_type: "I do not recommend this resource, having used it",
        reason: "I found it to be outdated and not very helpful.",
        likes: 1,
        dislikes: 7,
        tags: ["book", "outdated"],
        comments: [
            {
                user_name: "Eve",
                comment:
                    "Thanks for the heads-up. I was thinking of reading it.",
            },
        ],
    },
];
